import { RaphaelElement, RaphaelSet } from "raphael";
import { SymbolOptions, SymbolType } from "../options";
import Flowchart from "../chart";
export declare type Direction = "top" | "right" | "left" | "bottom";
export interface Position {
    x: number;
    y: number;
}
export default class FlowChartSymbol {
    chart: Flowchart;
    text: RaphaelElement<"SVG" | "VML", Element | SVGTextElement>;
    connectedTo: FlowChartSymbol[];
    group: RaphaelSet<"SVG" | "VML">;
    symbol?: RaphaelElement<"SVG" | "VML", Element | SVGRectElement>;
    symbolType: SymbolType;
    flowstate: string;
    key: string;
    lineStyle: Record<string, any>;
    leftLines: any[];
    rightLines: any[];
    topLines: any[];
    bottomLines: any[];
    bottomStart?: boolean;
    next?: any;
    next_direction: Direction | undefined;
    isPositioned?: boolean;
    width?: number;
    height?: number;
    topStart?: boolean;
    topEnd?: boolean;
    rightStart?: boolean;
    leftStart?: boolean;
    leftEnd?: boolean;
    rightEnd?: boolean;
    constructor(chart: Flowchart, options: SymbolOptions, symbol?: RaphaelElement<"SVG" | "VML", Element | SVGRectElement>);
    getAttr<T>(attName: string): T | undefined;
    initialize(): void;
    getCenter(): Position;
    getX(): number;
    getY(): number;
    shiftX(x: number): void;
    setX(x: number): void;
    shiftY(y: number): void;
    setY(y: number): void;
    getTop(): Position;
    getBottom(): Position;
    getLeft(): Position;
    getRight(): Position;
    render(): void;
    renderLines(): void;
    drawLineTo(symbol: FlowChartSymbol, text: string, direction?: Direction): void;
}
